version: "3.8"

services:
  app:
    container_name: application-${APP_NAME}
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        APP_PORT: "${APP_PORT}"
    volumes:
      - ./src:/app/src
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local-${APP_NAME}
    volumes:
      - ./docker/dynamodb-data:/home/dynamodblocal/data
    ports:
      - "${DYNAMODB_PORT}:${DYNAMODB_PORT}"
    user: root
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
